---
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - vars/test_vars.yml
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: ansible-role-postgresql
