---
- name: Verify
  hosts: all
  gather_facts: false
  become_user: "{{ postgresql_postgres_user }}"
  become: true
  vars_files:
    - vars/test_vars.yml
  tasks:
    - name: Verify data directory
      community.postgresql.postgresql_query:
        query: SHOW data_directory;
      when: postgresql_data_directory is defined
      register: __postgresql_test_tmp_result
      failed_when: __postgresql_test_tmp_result.query_result[0].data_directory != postgresql_data_directory

    - name: Retrieve postgresql_info
      community.postgresql.postgresql_info:
        filter: "!settings"
      register: __postgresql_test_tmp_result

    - name: Ensure database exists
      ansible.builtin.assert:
        that:
          - item in __postgresql_test_tmp_result.databases
      when: postgresql_databases is defined
      with_list: "{{ postgresql_databases }}"

    - name: Ensure user exists
      ansible.builtin.assert:
        that:
          - item in __postgresql_test_tmp_result.roles
      when: postgresql_users is defined
      with_list: "{{ postgresql_users }}"
